INSERT INTO Products (name, description, price, category) VALUES
                                                              ('Laptop', '15.6 inch laptop with Intel i5 processor and 8GB RAM', 799.99, 'Electronics'),
                                                              ('Smartphone', '5G enabled smartphone with 128GB storage', 699.99, 'Electronics'),
                                                              ('Wireless Headphones', 'Noise-cancelling over-ear headphones', 199.99, 'Electronics'),
                                                              ('Smartwatch', 'Water-resistant smartwatch with heart rate monitor', 149.99, 'Wearables'),
                                                              ('Tablet', '10-inch tablet with 64GB storage and WiFi connectivity', 329.99, 'Electronics'),
                                                              ('Bluetooth Speaker', 'Portable Bluetooth speaker with 10-hour battery life', 89.99, 'Audio'),
                                                              ('Digital Camera', 'Compact digital camera with 20MP sensor', 499.99, 'Photography'),
                                                              ('Gaming Console', 'Next-gen gaming console with 1TB storage', 499.99, 'Gaming'),
                                                              ('4K Television', '55-inch 4K UHD Smart TV', 999.99, 'Home Entertainment'),
                                                              ('Desktop Computer', 'All-in-one desktop with Intel i7 processor', 1199.99, 'Computers'),
                                                              ('Office Chair', 'Ergonomic office chair with lumbar support', 149.99, 'Furniture'),
                                                              ('Standing Desk', 'Adjustable height standing desk', 299.99, 'Furniture'),
                                                              ('LED Desk Lamp', 'LED desk lamp with adjustable brightness', 29.99, 'Home Office'),
                                                              ('Coffee Maker', '12-cup programmable coffee maker', 89.99, 'Appliances'),
                                                              ('Blender', 'High-speed blender with multiple settings', 59.99, 'Appliances'),
                                                              ('Vacuum Cleaner', 'Cordless vacuum cleaner with powerful suction', 179.99, 'Home Appliances'),
                                                              ('Air Purifier', 'HEPA air purifier for large rooms', 129.99, 'Home Appliances'),
                                                              ('Electric Toothbrush', 'Rechargeable electric toothbrush with smart features', 49.99, 'Personal Care'),
                                                              ('Hair Dryer', 'Professional hair dryer with ionic technology', 39.99, 'Personal Care'),
                                                              ('Fitness Tracker', 'Waterproof fitness tracker with GPS', 99.99, 'Wearables'),
                                                              ('Yoga Mat', 'Non-slip yoga mat with carrying strap', 29.99, 'Fitness'),
                                                              ('Treadmill', 'Folding treadmill with built-in workout programs', 899.99, 'Fitness Equipment'),
                                                              ('Dumbbell Set', 'Adjustable dumbbell set with 15 weight options', 159.99, 'Fitness Equipment'),
                                                              ('Electric Kettle', '1.7L electric kettle with auto shut-off', 29.99, 'Kitchen Appliances'),
                                                              ('Microwave Oven', 'Countertop microwave oven with 10 power levels', 129.99, 'Kitchen Appliances');